[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 1_000_000
gas_reports = ["HatsModule", "HatsModuleFactory"]
auto_detect_solc = false
solc = "0.8.18"
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "hats-protocol/=lib/hats-protocol/src/",
  "solady/=lib/solady/src/",
  "@openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

[profile.lite]
fuzz = { runs = 32 }
invariant = { runs = 10 }
# Speed up compilation and tests during development.
optimizer = false

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 2
wrap_comments = true

[rpc_endpoints]
local = "http://localhost:8545"

[etherscan]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config