[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 1_000_000
bytecode_hash = "none"
gas_reports = [
  "HatsModule",
  "HatsModuleFactory",
  "HatsEligibilitiesChain",
  "HatsTogglesChain",
]
auto_detect_solc = false
solc = "0.8.19"
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "hats-protocol/=lib/hats-protocol/src/",
  "solady/=lib/solady/src/",
  "@openzeppelin-contracts/=lib/openzeppelin-contracts/",
]

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

[profile.lite]
fuzz = { runs = 32 }
invariant = { runs = 10 }
# Speed up compilation and tests during development.
optimizer = false

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 2
wrap_comments = true

[rpc_endpoints]
arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_KEY}"
base-sepolia = "https://base-sepolia.infura.io/v3/${INFURA_KEY}"
gnosis = "${GC_RPC}"
local = "http://localhost:8545"
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
optimism = "https://optimism-mainnet.infura.io/v3/${INFURA_KEY}"
polygon = "${POLYGON_RPC}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"

[etherscan]
arbitrum = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=42161" }
base = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=8453" }
base-sepolia = {key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=84532"}
gnosis = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=100" }
mainnet = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=1" }
optimism = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=10" }
sepolia = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=11155111" }
polygon = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/v2/api?chainid=137" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
